# cocotb unit test for the ALU
SIM ?= icarus
TOPLEVEL_LANG ?= verilog

VERILOG_SOURCES = $(PWD)/../../src/alu.v
COCOTB_TOPLEVEL = alu
COCOTB_TEST_MODULES = test_alu

include $(shell cocotb-config --makefiles)/Makefile.sim